language: node_js
node_js:
  - "10.14.2"

cache: 
  npm: true
  directories:
    - "node_modules"

before_install:
  - echo "Installing Dependencies"

install: 
  - npm ci
  - npm install -g firebase-tools
  - npm install -g gatsby-cli

before_script:
  - echo "Running Build"

script:
  - GATSBY_ACTIVE_ENV=production gatsby build
  

after_success:
  - echo "Built Successfully"
  # - firebase use production
  # - firebase deploy --only hosting --token $FIREBASE_TOKEN

after_failure:

after_script:

before_deploy:
  - echo "Deploying"

deploy:
  provider: firebase
  token: 
    secure: $FIREBASE_TOKEN
  project: production

after_deploy:
  - echo "Deployed Successfully"
